version: "3.7"
services:

  front-envoy:
    image: envoyproxy/envoy:v1.21-latest
    container_name: envoy
    # Uncomment following for debug logs
    # command:
    # - --log-level debug
    # - --config-path /etc/envoy/envoy.yaml
    volumes:
      - ./envoy/${FRONT_ENVOY_YAML}:/etc/envoy/envoy.yaml
      - ./envoy/dynamic:/etc/envoy/dynamic
    networks:
    - envoymesh
    ports:
    - "8000:8000"
    # admin interface
    - "9901:9901"

  ext_authz-http-service:
    build:
      context: ./auth
      dockerfile: http-service/Dockerfile
    container_name: authz-http-service
    volumes:
    - ./users.json:/etc/users.json
    environment:
    - USERS=/etc/users.json
    networks:
    - envoymesh

  ext_authz-grpc-service:
    build:
      context: ./auth
      dockerfile: grpc-service/Dockerfile
    container_name: authz-grpc-service
    volumes:
    - ./users.json:/etc/users.json
    networks:
    - envoymesh

  ext_authz-opa-service:
    image: openpolicyagent/opa:0.37.2-istio
    container_name: authz-opa-service
    volumes:
    - ./config/opa-service/policy.rego:/etc/policy.rego
    command:
    - run
    - --log-level=debug
    - --server
    - --log-format=json-pretty
    - --set=plugins.envoy_ext_authz_grpc.addr=:9002
    - --set=decision_logs.console=true
    - /etc/policy.rego
    networks:
    - envoymesh

  upstream-service:
    image: kennethreitz/httpbin
    environment:
      - "GUNICORN_CMD_ARGS=\"--capture-output --error-logfile - --access-logfile - --access-logformat \"%(h)s %(t)s %(r)s %(s)s Host: %({Host}i)s}\"\""
    container_name: server
    networks:
    - envoymesh

  dex:
    image: ghcr.io/dexidp/dex:v2.31.0
    container_name: dex
    # Uncomment following to use another config
    # command:
    # - "dex serve"
    # - "/etc/dex/config.yaml"
    volumes:
      - ./dex/config.yaml:/etc/dex/config.docker.yaml
    # environment:
    # - DEX_ISSUER=http://127.0.0.1:5556/dex
    # - DEX_TELEMETRY_HTTP=0.0.0.0:5558
    # - DEX_LOG_LEVEL=info
    # - DEX_CONNECTORS_ENABLE_MOCK=true
    networks:
      envoymesh:
        aliases:
        # alias for envoy to reach dex jwks endpoint
        - "dex.127.0.0.1.nip.io"
    ports:
    # web interface
    - "5556:5556"
    # telemetry
    # - "5558:5558"

  upstream-websocket-service:
    build:
      context: ./websocket-server
    container_name: websocket-server
    networks:
    - envoymesh


networks:
  envoymesh:
    name: envoymesh
